### ISSUE TITLE
Task: Improvement for filterContentForSearchText function

### ISSUE THREAD

**Issue by Magnat12** [dgozhenko/Search#1]
Update function `filterContentForSearchText` to use `NSPredicate` for searching in array.
Push this changes to separate git branch (not *master*)

**Comment by dgozhenko** [comment]
I tried  but I couldn't do it

**Comment by dgozhenko** [comment]
Explain how to do it

**Comment by dgozhenko** [comment]
I did it!

**Comment by Magnat12** [comment]
You implementation incorrect: code, that you right still using old way to filter array. Code with `NSPredicate` is incorrect and junk in that case, because result never used.
